-- ====================================================================
-- Semilla 01: Catálogo de las 52 Fuentes Provinciales (BOPs)
-- Clasificación por tipo de acceso y estado inicial inactivo (activo = false)
-- ====================================================================

insert into public.fuentes (provincia, tipo, url_base, activo) values
('Araba/Álava', 'html', 'https://botha.araba.eus', false),
('Albacete', 'html', 'https://boletin.dipualba.es', false),
('Alicante', 'rss', 'https://www.dip-alicante.es/bop/', false),
('Almería', 'html', 'https://www.dipalme.org/bop/', false),
('Asturias', 'rss', 'https://sede.asturias.es/bopa', false),
('Ávila', 'pdf_fijo', 'https://www.diputacionavila.es/bop/', false),
('Badajoz', 'rss', 'https://www.dip-badajoz.es/bop/', false),
('Barcelona', 'rss', 'https://bop.diba.cat/', false),
('Burgos', 'html', 'https://www.diputaciondeburgos.es/bop/', false),
('Cáceres', 'rss', 'https://bop.dip-caceres.es/', false),
('Cádiz', 'html', 'https://www.dipucadiz.es/bop/', false),
('Cantabria', 'html', 'https://boc.cantabria.es/', false),
('Castellón', 'html', 'https://bop.dipcas.es/', false),
('Ciudad Real', 'html', 'https://bop.dipucr.es/', false),
('Córdoba', 'rss', 'https://bop.dipucordoba.es/', false),
('A Coruña', 'rss', 'https://bop.dacoruna.gal/', false),
('Cuenca', 'html', 'https://www.dipucuenca.es/bop', false),
('Girona', 'rss', 'https://www.ddgi.cat/bop/', false),
('Granada', 'html', 'https://www.dipgra.es/bop/', false),
('Guadalajara', 'html', 'https://boletin.dguadalajara.es/', false),
('Gipuzkoa', 'html', 'https://bog.gipuzkoa.eus/', false),
('Huelva', 'html', 'https://www.diphuelva.es/bop/', false),
('Huesca', 'html', 'https://www.dphuesca.es/bop', false),
('Illes Balears', 'rss', 'https://boib.caib.es/', false),
('Jaén', 'html', 'https://bop.dipujaen.es/', false),
('León', 'html', 'https://www.dipuleon.es/bop/', false),
('Lleida', 'rss', 'https://bop.diputaciolleida.cat/', false),
('Lugo', 'html', 'https://deputacionlugo.gal/bop/', false),
('Madrid', 'rss', 'https://www.bocm.es/', false),
('Málaga', 'rss', 'https://www.malaga.es/bop/', false),
('Murcia', 'rss', 'https://www.borm.es/', false),
('Navarra', 'rss', 'https://bon.navarra.es/', false),
('Ourense', 'html', 'https://bopo.depourense.es/', false),
('Palencia', 'html', 'https://www.diputaciondepalencia.es/bop', false),
('Las Palmas', 'html', 'https://www.boplaspalmas.net/', false),
('Pontevedra', 'rss', 'https://boppo.depo.gal/', false),
('La Rioja', 'rss', 'https://web.larioja.org/bor-portada/', false),
('Salamanca', 'html', 'https://www.diputaciondesalamanca.gob.es/bop/', false),
('Santa Cruz de Tenerife', 'html', 'https://www.bopsantacruzdetenerife.es/', false),
('Segovia', 'html', 'https://www.dipsegovia.es/bop', false),
('Sevilla', 'html', 'https://www.dipusevilla.es/bop/', false),
('Soria', 'html', 'https://bop.dipsoria.es/', false),
('Tarragona', 'rss', 'https://www.dipta.cat/bop/', false),
('Teruel', 'html', 'https://236ws.dpteruel.es/bop/', false),
('Toledo', 'html', 'https://www.diputoledo.es/bop', false),
('Valencia', 'rss', 'https://bop.dival.es/', false),
('Valladolid', 'html', 'https://bop.diputaciondevalladolid.es/', false),
('Bizkaia', 'html', 'https://bob.bizkaia.eus/', false),
('Zamora', 'html', 'https://bop.diputaciondezamora.es/', false),
('Zaragoza', 'html', 'https://bop.dpz.es/', false),
('Ceuta', 'pdf_fijo', 'https://www.ceuta.es/bocce/', false),
('Melilla', 'pdf_fijo', 'https://www.melilla.es/bome/', false)
on conflict do nothing;
